//! `oml.toml` manifest and `oml.lock` lockfile handling.
//!
//! The manifest format is a deliberately tiny subset of TOML — two flat
//! tables, string values only — hand-parsed with no external `toml`
//! dependency, in keeping with OverML's pitch of not dragging a fragmented
//! dependency tree into a project just to read a config file. It is not a
//! general TOML parser; `[package]`/`[dependencies]` with `key = "value"`
//! lines and `//` comments is the whole grammar.
//!
//! The lockfile pins each dependency by content hash (not just a version
//! string), so `omlpkg build` is reproducible: the exact bytes that were
//! type-checked and run are the ones recorded, closing the same "works on
//! my machine because my copy of the dependency silently drifted" gap that
//! motivates OverML's determinism story elsewhere.

use crate::error::{OResult, OverMlError};
use crate::rng::Fnv1a;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct Manifest {
    pub name: String,
    pub version: String,
    pub entry: String,
    /// module name -> path, relative to the manifest's own directory
    pub dependencies: HashMap<String, String>,
}

pub fn parse_manifest(src: &str) -> OResult<Manifest> {
    let mut section = String::new();
    let mut name: Option<String> = None;
    let mut version: Option<String> = None;
    let mut entry = "main.oml".to_string();
    let mut deps = HashMap::new();

    for raw_line in src.lines() {
        let line = strip_comment(raw_line).trim();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('[') {
            let end = line
                .find(']')
                .ok_or_else(|| OverMlError::detached(format!("malformed section header: '{}'", line)))?;
            section = line[1..end].trim().to_string();
            continue;
        }
        let (key, val) = line
            .split_once('=')
            .ok_or_else(|| OverMlError::detached(format!("expected 'key = value', found '{}'", line)))?;
        let key = key.trim().to_string();
        let val = val.trim().trim_matches('"').to_string();
        match section.as_str() {
            "package" => match key.as_str() {
                "name" => name = Some(val),
                "version" => version = Some(val),
                "entry" => entry = val,
                _ => {}
            },
            "dependencies" => {
                deps.insert(key, val);
            }
            other => {
                return Err(OverMlError::detached(format!(
                    "unknown manifest section '[{}]'",
                    other
                )))
            }
        }
    }

    Ok(Manifest {
        name: name.ok_or_else(|| OverMlError::detached("oml.toml: missing [package] name"))?,
        version: version.unwrap_or_else(|| "0.0.0".to_string()),
        entry,
        dependencies: deps,
    })
}

fn strip_comment(line: &str) -> &str {
    match line.find("//") {
        Some(i) => &line[..i],
        None => line,
    }
}

/// Resolve every entry in `[dependencies]` to an absolute directory path,
/// relative to the manifest's own directory.
pub fn resolve_dependency_paths(manifest: &Manifest, manifest_dir: &Path) -> HashMap<String, PathBuf> {
    manifest
        .dependencies
        .iter()
        .map(|(name, rel)| (name.clone(), manifest_dir.join(rel)))
        .collect()
}

/// Content-hash every resolved dependency's `lib.oml` and write `oml.lock`
/// next to the manifest. Returns an error if a declared dependency has no
/// `lib.oml`.
pub fn write_lockfile(
    manifest: &Manifest,
    resolved: &HashMap<String, PathBuf>,
    manifest_dir: &Path,
) -> OResult<PathBuf> {
    let mut out = String::new();
    out.push_str("# generated by omlpkg — do not edit by hand\n\n");
    out.push_str("[package]\n");
    out.push_str(&format!("name = \"{}\"\n", manifest.name));
    out.push_str(&format!("version = \"{}\"\n\n", manifest.version));

    let mut names: Vec<&String> = resolved.keys().collect();
    names.sort();
    for name in names {
        let dir = &resolved[name];
        let lib = dir.join("lib.oml");
        let bytes = std::fs::read(&lib)
            .map_err(|e| OverMlError::detached(format!("cannot lock dependency '{}': {}", name, e)))?;
        let mut h = Fnv1a::new();
        h.write(&bytes);
        out.push_str("[[dependency]]\n");
        out.push_str(&format!("name = \"{}\"\n", name));
        out.push_str(&format!("path = \"{}\"\n", dir.display()));
        out.push_str(&format!("content_hash = \"fnv1a:{}\"\n\n", h.finish_hex()));
    }

    let lock_path = manifest_dir.join("oml.lock");
    std::fs::write(&lock_path, out)?;
    Ok(lock_path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_manifest() {
        let src = r#"
            [package]
            name = "demo"
            version = "0.1.0"
            entry = "main.oml"

            [dependencies]
            linalg = "../linalg"
        "#;
        let m = parse_manifest(src).unwrap();
        assert_eq!(m.name, "demo");
        assert_eq!(m.version, "0.1.0");
        assert_eq!(m.entry, "main.oml");
        assert_eq!(m.dependencies.get("linalg").unwrap(), "../linalg");
    }

    #[test]
    fn defaults_entry_and_version() {
        let src = "[package]\nname = \"x\"\n";
        let m = parse_manifest(src).unwrap();
        assert_eq!(m.entry, "main.oml");
        assert_eq!(m.version, "0.0.0");
    }

    #[test]
    fn rejects_missing_name() {
        let src = "[package]\nversion = \"0.1.0\"\n";
        assert!(parse_manifest(src).is_err());
    }
}
